name: Release

on:
  push:
    branches:
      - auto-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish docker image to GPR
        uses: machine-learning-apps/gpr-docker-publish@v1.3
        id: docker
        with:
          IMAGE_NAME: 'test-docker-action'
          TAG: ${{ github.ref }}
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: '/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
